# DO NOT EDIT THIS FILE!
#
# Python module org__POA generated by omniidl

import omniORB
omniORB.updateModule("org__POA")

# ** 1. Stub files contributing to this module
import ods52_idl

# ** 2. Sub-modules
import asam

# ** 3. End
