# DO NOT EDIT THIS FILE!
#
# Python module org__POA.asam generated by omniidl

import omniORB
omniORB.updateModule("org__POA.asam")

# ** 1. Stub files contributing to this module
import ods52_idl

# ** 2. Sub-modules
import ods

# ** 3. End
