# DO NOT EDIT THIS FILE!
#
# Python module org.asam.ods generated by omniidl

import omniORB
omniORB.updateModule("org.asam.ods")

# ** 1. Stub files contributing to this module
import ods52_idl

# ** 2. Sub-modules

# ** 3. End
